USE db_dictionaries;

-- ================
-- Lista de tipo de palabras
-- ================

INSERT INTO 
    tbl_type_word (NAME) 
VALUES
    ("Sustantivo"),
    ("Verbo"),
    ("Adjetivo"),
    ("Adverbio"),
    ("Pronombre"),
    ("Preposición"),
    ("Interjección / expresion"),
    ("Artículo"),
    ("Conjunción");

SELECT * FROM tbl_type_word;

-- ================
-- Diccionarios
-- ================

INSERT INTO
    tbl_dictionaries (NAME) 
VALUES
    ("ULTREA");

SELECT * FROM tbl_dictionaries;

-- ================
-- Lista de palabras
-- ================
INSERT INTO 
    tbl_words (WORD,PRONUNCIATION,SIGNIFICANCE,ID_DICTIONARY) 
VALUES
("Achatrë","a-'t͡ʃa-tɾə","Cerebro",1),
("Adartë","a-'daɾ-tə","Estrella",1),
("Adrieh","a-'dɾiex","Pronto (adverbio)",1),
("Afinni","a-'fin-ni","Mañana (día posterior)",1),
("Ajatsë","'a-ʒa-t͡sə","Energía",1),
("Ajaxetsem","a-'ʒa-ʃe-t͡sem","Energía cósmica",1),
("Ajile","'a-ʒi-le","Antes (adverbio)",1),
("Akälian","a-'kæ-lian","Brillo / Fulgor /  Fulgor (deidad)",1),
("Akälian(ëj)","a-'kæ-lia-n(əʒ)","Brillante / Fulgente /  Relativo a El Fulgor (deidad)",1),
("Alidue","a-li-'du-e","Espacio",1),
("Ällin","'æl-lin","Tiempo",1),
("Amek","a-'mek","Poco (adverbio)",1),
("Ankiex","an-'kieʃ","Hueso",1),
("Apriza","a-'pɾi-za","Bien / bondad",1),
("Arüviezdi","a-rɯ-'viez-di","Confederación",1),
("Assifüt","as-'si-fɯt","Himno",1),
("Assop","as-'sop","Montaña",1),
("Assüc","as-'sɯθ","Cerca (adverbio)",1),
("Assüc(ëj)","as-'sɯ-θ(əʒ)","Cercano (adjetivo)",1),
("Atsal","a-'t͡sal","Bien (adverbio)",1),
("Atsal(ëj)","a-'t͡sa-l(əʒ)","Bueno (adjetivo)",1),
("Atyal","a-'tjal","Norte",1),
("Aurexoü","au-ɾe-'ʃo-ɯ","Ectoplasma (forma de  materia)",1),
("Ayeul(ëj)","a-'jeu-l(əʒ)","Igual (adjetivo)",1),
("Ayeulim","a-'jeu-lim","Igualdad",1),
("Ayütsa","a-'jɯ-t͡sa","Maestro",1),
("Azigül","a-'zi-gɯl","Bronce",1),
("Bafrëd","ba-'fɾəd","Canción",1),
("Bägej","bæ-'geʒ","Traer  (verbo)",1),
("Bämklië","bæm-'kliə","Abuela",1),
("Bäntrë","'bæn-tɾə","Madre",1),
("Beceit","be-'θeit","Importancia",1),
("Beceit(ëj)","be-'θei-t(əʒ)","Importante  (adjetivo)",1),
("Bidë","'bi-də","Día",1),
("Bidjim","'bid-ʒim","Comida",1),
("Bimjën","'bim-ʒən","Comer  (verbo)",1),
("Biöja","'biʌ-ʒa","Izquierda",1),
("Birah(ëj)","'bi-ɾa-x(əʒ)","Hermoso  (adjetivo)",1),
("Birahië","bi-'ɾa-xiə","Hermosura",1),
("Bissal","bis-'sal","Pedir  / rogar (verbo)",1),
("Bläyet(ëj)","blæ-'je-t(əʒ)","Enorme  / gigante (adjetivo)",1),
("Blicareu","bli-θa-'ɾe-u","Gobierno",1),
("Bonnie","'bon-nie","Regular  (adverbio)",1),
("Börzël","bʌɾ-'zəl","Recibir  (verbo)",1),
("Brëfac","'bɾə-faθ","Necesitar  (verbo)",1),
("Brëv(ëj)","bɾə-'v(əʒ)","Caluroso  (adjetivo)",1),
("Brëvik","bɾə-'vik","Acalorar  (verbo)",1),
("Brëvui","bɾə-'vui","Calor  (ambiental)",1),
("Brilallid","bɾi-'lal-lid","Manejar  / conducir
  (verbo)",1),
("Bripset","bɾip-'set","Viajar  (verbo)",1),
("Bücëklexar","bɯ-'θə-kle-ʃaɾ","Purga  de creencias",1),
("Bücëyë","bɯ-'θə-jə","Purga  / depuración",1),
("Büchigrët-klëvi","bɯ-t͡ʃi-'gɾət‿kləvi","Comportarse  (verbo)",1),
("Buxilo","bu-'ʃi-lo","Oreja",1),
("Calzën","'θal-zən","Correr  (verbo)",1),
("Cärin","θæ-'ɾin","Orden",1),
("Cärin(ëj)","θæ-ɾi-'n(əʒ)","Ordenado  (adjetivo)",1),
("Cäriniv","'θæ-ɾi-niv","Ordenar  (verbo)",1),
("Cëktua","θək-'tu-a","Lágrima",1),
("Cëpdux","'θəp-duʃ","Sueño  / somnolencia",1),
("Cëpt","θəpt","Dormir (verbo)",1),
("Cëpt(ëj)","θəp-'t(əʒ)","Dormido  (adjetivo)",1),
("Chassëxrëi","t͡ʃas-'sə-ʃɾəi","Federación",1),
("Chëh","t͡ʃəx","Hablar  (verbo)",1),
("Chëhat","t͡ʃə-'xat","Hablante",1),
("Chilae","'t͡ʃi-la-e","Cuerpo",1),
("Chivic","t͡ʃi-'viθ","Afuera  (adverbio)",1),
("Cijav","θi-'ʒav","Flor",1),
("Cillür","θil-'luɾ","Tristeza",1),
("Cillür(ëj)","θil-'lɯ-r(əʒ)","Triste  (adjetivo)",1),
("Ciön","θiʌn","Con  / por (preposición)",1),
("Cirj","θiɾʒ","Haber  (inanimado) (verbo)",1),
("Cisyal(ëj)","θi-'sja-l(əʒ)","Sagrado  (adjetivo)",1),
("Civüa","θi-'vɯa","Derecha",1),
("Credilë","'θɾe-di-lə","Idioma",1),
("Cübrë","'θɯ-bɾə","Tarde  (momento del día)",1),
("Cücün","'θɯ-θɯn","Tu/tuyo  (pronombre)",1),
("Cün","θɯn","Tú  (pronombre)",1),
("Cuvrän","θu-'vɾæn","Trabajar  (verbo)",1),
("Cuvrili","θu-'vɾi-li","Trabajo",1),
("Cyonmih","'θjon-mix","Unir  (verbo)",1),
("Dabrez","ða-'bɾez","Leer  (verbo)",1),
("Dabria","'ða-bɾia","Libro",1),
("Däsfij","'ðæs-fiʒ","Volar (verbo)",1),
("Dattip","'ðat-tip","Vivir  (en un lugar)
  (verbo)",1),
("Decyër","ðe-'θjəɾ","Paz",1),
("Dërë","'ðə-ɾə","Expresión de asombro  (interjección)",1),
("Detan(ëj)","ðe-ta-'n(əʒ)","Simple / sencillo  (adjetivo)",1),
("Detanaü","ðe-ta-'na-ɯ","Simpleza / sencillez",1),
("Diech(ëj)","'ðie-t͡ʃ(əʒ)","Limpio (adjetivo)",1),
("Diechöch","ðie-'t͡ʃʌt͡ʃ","Limpiar (verbo)",1),
("Diechyoh","'ðie-t͡ʃjox","Limpieza",1),
("Dillizaur","ðil-li-'za-uɾ","Ofender (verbo)",1),
("Dillizayu","ðil-li-'za-ju","Ofensa",1),
("Diuca","'ðiu-θa","Hombre",1),
("Divlü","'ði-vlɯ","Viento",1),
("Döhixa","ðʌ-'xi-ʃa","Atrás (adverbio)",1),
("Driv","driv","Ser / estar  (verbo)",1),
("Druja","'ðɾu-ʒa","Ciudad",1),
("Drulë","'ðɾu-lə","Todo (adverbio)",1),
("Drupatsim","ðɾu-pa-'t͡sim","Urbanización",1),
("Dugüst","ðu-'gɯst","Metal",1),
("Dulne","'ðul-ne","Poco (adverbio)",1),
("Düncü","'ðɯn-θɯ","Su/suyo (ustedes)  (pronombre)",1),
("Dünu","'ðɯ-nu","Ustedes (pronombre)",1),
("Dutächti","ðu-'tæt͡ʃ-ti","Dedo de la mano",1),
("Dutächye","ðu-'tæ-t͡ʃje","Dedo del pie",1),
("Dyaröv","ðja-'ɾʌv","Pueblo (etnología)",1),
("Ëbugya","ə-'bu-gja","Nada (concepto)",1),
("Ëch","ət͡ʃ","Para (preposición)",1),
("Edrich","e-'dɾit͡ʃ","Todos (pronombre)",1),
("Egartsë","E-'gaɾ-t͡sə","Carne",1),
("Egazëm","e-'ga-zəm","Gloria",1),
("Eizün","'ei-zɯn","Río",1),
("Eklic","e-'kliθ","Plata",1),
("Ekrich(ëj)","e-kɾi-'t͡ʃ(əʒ)","Plateado (adjetivo)",1),
("Ekrichäl","e-'kɾi-t͡ʃal","Plateado",1),
("Elice","e-'li-θe","Oeste",1),
("Eligr(ëj)","e-li-'gɾ(əʒ)","Lento (adjetivo)",1),
("Eligrea","e-li-'gɾe-a","Despacio (adverbio)",1),
("Eligrüja","e-li-'gɾɯ-ʒa","Lentitud",1),
("Ëlirë","'ə-li-ɾə","Punto (ortotipo-  gráfico)",1),
("Elpë","'el-pə","Dónde (adverbio)",1),
("Eoriëv","e-'o-ɾiəv","Sílaba",1),
("Epüg","e-'pɯg","Boca",1),
("Erijet","e-ɾi-'ʒet","Puerta",1),
("Esuftë","e-'suf-tə","Guerra",1),
("Ëtsk(ëj)","'ət͡s-k(əʒ)","Grande (adjetivo)",1),
("Ettier","et-'tieɾ","Animal",1),
("Evërdih","e-'vəɾ-dix","Incendio",1),
("Evië","'e-viə","Fuego",1),
("Evuad(ëj)","e-'vua-d(əʒ)","Bello (adjetivo)",1),
("Evuadë","e-'vua-də","Belleza",1),
("Evüre","'e-vɯ-ɾe","Todavía / aún (adverbio)",1),
("Ezalye","e-'za-lje","Pie",1),
("Facedël","fa-'θe-dəl","Consciencia (sentido)",1),
("Fävrät","fæ-'vɾæt","Llamar (nombres) (verbo)",1),
("Faxel(ëj)","fa-ʃe-'l(əʒ)","Asqueroso (adjetivo)",1),
("Faxellu","fa-'ʃel-lu","Asco",1),
("Faxelüch","fa-ʃe-'lɯt͡ʃ","Asquearse (verbo)",1),
("Faztrië","'faz-tɾiə","Hola",1),
("Fegnië","'feg-niə","Amigo",1),
("Feibrëi","'fei-bɾəi","Imaginación",1),
("Feibrër","fei-'bɾəɾ","Imaginar (verbo)",1),
("Felinhur","'fe-lin-xuɾ","Regalar (verbo)",1),
("Felinjëi","fe-lin-'ʒəi","Regalo",1),
("Fëzzik","'fəz-zik","Elevarse / alzarse",1),
("Fëzzik(ëj)","fəz-'zi-k(əʒ)","Elevado / alzado  (adjetivo)",1),
("Fibrildü","fi-'bɾil-dɯ","Aeronave",1),
("Fideg(ëj)","'fi-de-g(əʒ)","Marrón (adjetivo)",1),
("Fidegrök","'fi-de-gɾʌk","Marrón",1),
("Fiennë","'fien-nə","Dios",1),
("Fihzib","'fix-zib","Desaprobar (verbo)",1),
("Fiskaznë","fis-'kaz-nə","Tormenta",1),
("Fixkelö","fiʃ-'ke-lʌ","Nube",1),
("Fraxtöyebda","fɾaʃ-'tʌ-jeb-da","Parlamento",1),
("Frizëd","fɾi-'zəd","Traer algo con regularidad  (verbo)",1),
("Fryëvëch","fɾjə-'vət͡ʃ","Integrar (verbo)",1),
("Fryëvhët","'fɾjəv-xət","Integración",1),
("Fudxer","fud-'ʃeɾ","Cansar (verbo)",1),
("Fudxer(ëj)","fud-ʃe-'ɾ(əʒ)","Cansado (adjetivo)",1),
("Fudxica","fud-'ʃi-θa","Cansancio",1),
("Futtël","fut-'təl","Curar (verbo)",1),
("Gämdue","'gæm-due","Espacio exterior",1),
("Gänjek","gæn-'ʒek","Mirar / ver (verbo)",1),
("Gariz(ëj)","ga-'ɾi-z(əʒ)","Feliz (adjetivo)",1),
("Garizië","ga-'ɾi-ziə","Felicidad",1),
("Gart","gaɾt","Muy (adverbio)",1),
("Gavüt","ga-'vɯt","Hoy",1),
("Gaznë","'gaz-nə","Lluvia",1),
("Gaznür","'gaz-nɯɾ","Llover (verbo)",1),
("Gelcü","'gel-θɯ","Su/suyo (ellos)  (pronombre)",1),
("Gële","'gə-le","Ellos (pronombre)",1),
("Gextra","'geʃ-tɾa","Cara",1),
("Gixel","gi-'ʃel","Cerrar (verbo)",1),
("Gizün(ëj)","gi-'zɯ-n(əʒ)","Verde (adjetivo)",1),
("Gizünän","gi-'zɯ-næn","Verde",1),
("Glabyöchez","gla-'bjʌ-t͡ʃez","Estructura  (arquitectónica)",1),
("Glamäriz","gla-'mæ-ɾiz","Surgir (verbo)",1),
("Goirüj","goi-'ɾɯʒ","Afiliar / asociar (verbo)",1),
("Goxë","'go-ʃə","Mierda (interjección)",1),
("Grächic","gɾæ-'t͡ʃiθ","Esconder (verbo)",1),
("Grärva","'gɾæɾ-va","Anciano / anciana",1),
("Graüvej","gɾa-'ɯ-veʒ","Impulsar (verbo)",1),
("Graüvil","gɾa-'ɯ-vil","Impulso",1),
("Graxyuraz","gɾa-'ʃju-ɾaz","Vocabulario",1),
("Güjagap","gɯ-ʒa-'gap","Crear caos (verbo)",1),
("Güjak(ëj)","gɯ-ʒa-'k(əʒ)","Caótico (adjetivo)",1),
("Güjakre","gɯ-'ʒa-kɾe","Caos",1),
("Guvuch","gu-'vut͡ʃ","Absorber (verbo)",1),
("Hakegrëv","xa-ke-'gɾəv","Alejar (verbo)",1),
("Haliep","xa-'liep","Peor (adverbio)",1),
("Hanägev","xa-'næ-gev","Capital",1),
("Häppax","'xæp-paʃ","Moldear (verbo)",1),
("Hassig","xas-'sig","Deber (verbo)",1),
("Hätad(ëj)","'xæ-ta-d(əʒ)","Diminuto (adjetivo)",1),
("Hatsel","'xa-t͡sel","Lastimadura / herida",1),
("Haxrat","xa-'t͡ʃɾat","Persona",1),
("Heilëmuc","'xei-lə-muθ","Constituir (verbo)",1),
("Hësside","'xəs-si-de","Anterior",1),
("Het","xet","Artículo determinado",1),
("Hëzix","'xə-ziʃ","Llorar (verbo)",1),
("Hibridüe","xi-bɾi-'dɯ-e","Vehículo",1),
("Hicex","xi-'θeʃ","Pero (conjunción)",1),
("Hiejän","'xie-ʒæn","Ganar (verbo)",1),
("Hisil(ëj)","xi-'si-l(əʒ)","Ruidoso (adjetivo)",1),
("Hisillë","'xi-sil-lə","Sonido / ruido",1),
("Hiträt","'xi-træt","Terminar / finalizar  (verbo)",1),
("Hiyëxa","xi-'jə-ʃa","Límite",1),
("Hogüts","xo-'gɯt͡s","Enseñar (verbo)",1),
("Hoxdar","xoʃ-'daɾ","Querer (verbo)",1),
("Höyajis","xʌ-'ja-ʒis","Librar (verbo)",1),
("Hrijët","xɾi-'ʒət","Mente",1),
("Hüdir(ëj)","xɯ-'di-ɾ(əʒ)","Dimensional (física)  (adjetivo)",1),
("Hüdireb","'xɯ-di-ɾeb","Dimensión (física)",1),
("Hüt","xɯt","Qué (pronombre)",1),
("Huznik","xuz-'nik","Llevar algo con  regularidad (verbo)",1),
("Iajöge","ia-'ʒʌ-ge","Hombro",1),
("Ibaxutan","i-ba-'ʃu-tan","Tentación",1),
("Icage","i-'θa-ge","Ojo",1),
("Icüe","i-'θɯ-e","Nunca / jamás (adverbio)",1),
("Idänyu","i-'dæ-nju","Diente",1),
("Iëbatrë","iə-'ba-tɾə","Nación / patria",1),
("Iflentu","i-'flen-tu","Alma / espíritu  (abstracción)",1),
("Igexänzah","i-ge-'ʃæn-zax","Dignidad",1),
("Ijasëtsa","i-ʒa-'sə-t͡sa","Escuela / colegio",1),
("Ikkiu","'ik-kiu","Piel",1),
("Inzält","in-'zælt","Culto",1),
("Inzält(ëj)","in-'zæl-t(əʒ)","Relativo al culto /  eclesiástico (adjetivo)",1),
("Iseid(ëj)","i-'sei-d(əʒ)","Angustiado (adjetivo)",1),
("Iseidax","i-'sei-daʃ","Angustiar (verbo)",1),
("Iseidax","i-sei-'daʃ","Angustia",1),
("Isizöre","i-si-'zʌ-ɾe","Origen",1),
("Itäd(ëj)","i-'tæ-d(əʒ)","Blanco (adjetivo)",1),
("Itäda","i-'tæ-da","Blanco",1),
("Itsyëc","'i-t͡sjəθ","Joven",1),
("Itsyëhu","i-'t͡sjə-xu","Juventud",1),
("Itüres","i-'tɯ-ɾes","Cierto (adverbio)",1),
("Iukruxat","'iu-kɾu-ʃat","Tecnología",1),
("Ixai","i-'ʃai","Más (adverbio)",1),
("Ixgorië","Iʃ-'go-ɾiə","Rayo",1),
("Ixkudën","iʃ-ku-'dən","Dialecto",1),
("Izäryë","i-'zæ-ɾjə","Música",1),
("Izurva","i-'zuɾ-va","Por igual (adverbio)",1),
("Jakkär","'ʒak-kaɾ","Comprar (verbo)",1),
("Jäkördi","ʒæ-'kʌɾ-di","Victoria",1),
("Jämac","'ʒæ-maθ","Empezar / comenzar (verbo)",1),
("Jämau","ʒæ-'ma-u","Comienzo / inicio",1),
("Järyom","'ʒæɾ-jom","Arma",1),
("Javamrüklia","ʒa-vam-'ɾɯ-klia","Derecho (reconocimiento)",1),
("Jëlariu","ʒə-'la-riu","Recién (adverbio)",1),
("Jemprë","'ʒem-pɾə","Gracias",1),
("Jezul","ʒe-'zul","Quizás / tal vez  (adverbio)",1),
("Jicklië","ʒiθ-'kliə","Abuelo",1),
("Jidëk","ʒi-'dək","Cuánto (adverbio)",1),
("Jiëtsëv","ʒiə-'t͡səv","Suceder (verbo)",1),
("Jilö","'ʒi-lʌ","Casa",1),
("Jimmäg","ʒim-'mæg","Inspirar (verbo)",1),
("Jiztrë","'ʒiz-tɾə","Padre",1),
("Jös","ʒʌs","No (adverbio)",1),
("Jocäzyeg","ʒo-'θæ-zjeg","Tamaño",1),
("Jölidrë","ʒʌ-'li-dɾə","Muerte",1),
("Jöllur","'ʒʌl-luɾ","Morir (verbo)",1),
("Jözu","'ʒʌ-zu","Negación verbal (adverbio)",1),
("Jötbeh","'ʒʌt-bex","Inventar / fabricar  (verbo)",1),
("Jottrüna","'ʒot-tɾɯ-na","Sustantivo",1),
("Joyetix","ʒo-'je-tiʃ","Emanar energía / generar  energía (verbo)",1),
("Jumer","ʒu-'meɾ","Nieve",1),
("Jumräj","ʒu-'mɾæʒ","Nevar (verbo)",1),
("Junlio","'ʒun-li-o","Hielo",1),
("Juräör","ʒu-'ɾæ-ʌɾ","Hora",1),
("Kälcut","kæl-'θut","Venir (verbo)",1),
("Kän","kæn","Vocativo informal  (interjección)",1),
("Kätsa","'kæ-t͡sa","Exacto (adverbio)",1),
("Katsüz","ka-'t͡sɯz","Vivir (biologicamente)  (verbo)",1),
("Käuze","'kæu-ze","Mujer",1),
("Kazië","'ka-ziə","Vida (biológica)",1),
("Këciur(ëj)","kə-'θiu-ɾ(əʒ)","Sucio (adjetivo)",1),
("Këciuret","kə-'θiu-ɾet","Ensuciar (verbo)",1),
("Këciurt","kə-'θiuɾt","Suciedad",1),
("Kimp","kimp","Subir (verbo)",1),
("Kinnech","kin-'net͡ʃ","Habitar / poblar (verbo)",1),
("Kirzët","kiɾ-'zət","Ir (verbo)",1),
("Klarëij","kla-'ɾəiʒ","Abuelos/  abuelas",1),
("Klë","klə","Él/ella (pronombre)",1),
("Klëcü","'klə-θɯ","Su/suyo (él/ella)  (pronombre)",1),
("Klexaj","kle-'ʃaʒ","Creer (verbo)",1),
("Klexajat","kle-'ʃa-ʒat","Creyente",1),
("Klexaryë","kle-'ʃa-ɾjə","Creencia",1),
("Kotsüdir","ka-t͡sɯ-'diɾ","Acercar (verbo)",1),
("Krëch","kɾət͡ʃ","Decir (verbo)",1),
("Kruxh(ëj)","'kɾuʃ-x(əʒ)","Enojado / enfadado  (adjetivo)",1),
("Kruxhöb","kɾuʃ-'xʌb","Enojarse / enfadar (verbo)",1),
("Kruxih","kɾu-'ʃix","Enojo / enfado",1),
("Kuichux","'kui-t͡ʃuʃ","Apreciar / atesorar  (verbo)",1),
("Kunäbnë","'ku-næb-nə","Primo/  prima materna/a",1),
("Kunijnë","'ku-niʒ-nə","Primo/  prima paterno/a",1),
("Kuvrat","ku-'vɾat","Quién (pronombre)",1),
("Laberëts(ëj)","la-be-'ɾə-t͡s(əʒ)","Encomendado (adjetivo)",1),
("Laberëtsat","la-be-'ɾə-t͡sat","Encomienda / encomendación",1),
("Lachëc","la-'t͡ʃəθ","Silencio",1),
("Lachëc(ëj)","la-'t͡ʃə-θ(əʒ)","Silencioso (adjetivo)",1),
("Lädvezi","læd-'ve-zi","Nieta",1),
("Lägyur","læ-'gjuɾ","Palabra",1),
("Laichaj","lai-'t͡ʃaʒ","Salir (verbo)",1),
("Latrüd","la-'tɾɯd","Pensar (verbo)",1),
("Latrütai","la-'tɾɯ-tai","Pensamiento",1),
("Lätsöd","'læt-sʌd","Hija",1),
("Läzhit","'læz-xit","Descubrir (verbo)",1),
("Lëhër","'lə-xəɾ","Elegir (verbo)",1),
("Lëhër(ëj)","lə-'xə-ɾ(əʒ)","Elegido (adjetivo)",1),
("Lerät","le-'ɾæt","Cuándo (adverbio)",1),
("Lexbrë","'leʃ-bɾə","También / tampoco  (adverbio)",1),
("Licej","li-'θeʒ","Usar  (verbo)",1),
("Limyüa","li-'mjɯa","Hierro",1),
("Lincea","lin-'θe-a","Esfera",1),
("Littya","'lit-tya","Mano",1),
("Lochäht","lo-'t͡ʃæxt","Consonante",1),
("Lotrug","lo-'tɾug","Nada (pronombre)",1),
("Lümic","lɯ-'miθ","Despertar (verbo)",1),
("Lümic(ëj)","'lɯ-mi-  θ(əʒ)","Despierto (adjetivo)",1),
("Lunjilë","lun-'ʒi-lə","Familia",1),
("Lyätteb","'lyæt-teb","Funcionar  (verbo)",1),
("Lyëche","'ljə-t͡ʃe","Salud",1),
("Lyetsëid","'lje-t͡səid","Consciencia  (valor cósmico)",1),
("Lyü","ljɯ","O (conjunción)",1),
("Madxirië","mad-'ʃi-ɾiə","Electricidad",1),
("Mägrez","mæ-'gɾez","Permitir (verbo)",1),
("Mahaü","ma-'xa-ɯ","Año",1),
("Mai","mai","Expresión interrogativa  (interjección)",1),
("Maitän","'mai-tæn","Conocer (verbo)",1),
("Mejaldrü","me-'ʒal-dɾɯ","Información",1),
("Miatrix","mia-'tɾiʃ","Jugar (verbo)",1),
("Michël","mi-'t͡ʃəl","Caminar (verbo)",1),
("Missër","mis-'səɾ","Crear (verbo)",1),
("Missërat","mis-'sə-ɾat","Creador",1),
("Missërui","mis-sə-'ɾui","Creación",1),
("Mix(ëj)","mi-'ʃ(əʒ)","Rojo (adjetivo)",1),
("Mixan","mi-'ʃan","Rojo",1),
("Moir(ëj)","moi-'ɾ(əʒ)","Hambriento (adjetivo)",1),
("Moiruv","'moi-ɾuv","Hambre",1),
("Mrugai","mru-'gai","Pregunta",1),
("Mrugël","mɾu-'gəl","Preguntar (verbo)",1),
("Mryëk","mɾjək","Tener (verbo)",1),
("Mücir","mɯ-'θiɾ","Llevar (verbo)",1),
("Mudrëföt","'mu-dɾə-fʌt","Religión",1),
("Müikau","mɯi-'ka-u","Truco",1),
("Murjün","'muɾ-ʒɯn","Océano/  mar",1),
("Muxir","mu-'ʃiɾ","Escuchar / oír (verbo)",1),
("Myatap","'mja-tap","Arena",1),
("Myuch(ëj)","'mju-t͡ʃ(əʒ)","Oficial (adjetivo)",1),
("Myuchalt","'mju-t͡ʃalt","Oficialidad",1),
("Nädir","'næ-diɾ","Agarrar (verbo)",1),
("Nädraj","næ-'dɾaʒ","Tierra",1),
("Nägrid","'næ-gɾid","Además (adverbio)",1),
("Nahlün","'nax-lɯn","Cascada",1),
("Nalänia","na-'læ-nia","Planta",1),
("Nallëz","'nal-ləz","Bendecir (verbo)",1),
("Nanfil(ëj)","'nan-fi-ləʒ","Desordenado (adjetivo)",1),
("Nanfilan","'nan-fi-lan","Desorden",1),
("Nanfiler","nan-'fi-leɾ","Desordenar (verbo)",1),
("Navlüx","na-'vlɯʃ","Pensar  (verbo)",1),
("Nëivyats","'nəi-vjat͡s","Identidad",1),
("Nëlj","nəlʒ","Haber (animado) (verbo)",1),
("Nichau","'ni-t͡ʃa-u","Olor",1),
("Nichaz","ni-'t͡ʃaz","Oler",1),
("Nidälxe","ni-'dæl-ʃe","Fruta",1),
("Nizärya","ni-'zæ-ɾya","Cultura",1),
("Nizchivhüditsëb","niz-t͡ʃiv-'xɯ-di-t͡səb","Mundo extradimensional",1),
("Nizitsë","ni-'zi-t͡sə","Mundo",1),
("Nosir(ëj)","'no-si-ɾ(əʒ)","Miedoso / temeroso  (adjetivo)",1),
("Nosirü","no-'si-ɾɯ","Miedo / temor",1),
("Nosirül","no-'si-ɾɯl","Atemorizar (verbo)",1),
("Nulü","'nu-lɯ","Menos (adverbio)",1),
("Nürch","nɯɾt͡ʃ","Entender (verbo)",1),
("Nurchib","nuɾ-'t͡ʃib","Parar (tras estar sentado)  (verbo)",1),
("Nüsovah","'nɯ-so-vax","Gris",1),
("Nyüctul","'njɯθ-tul","Enviar (verbo)",1),
("Oajës(ëj)","o-a-'ʒə-s(əʒ)","Difícil / complejo  (adjetivo)",1),
("Oajëse","o-a-'ʒə-se","Dificultad / complejidad",1),
("Ochär","o-'t͡ʃæɾ","Lengua",1),
("Ocurvië","o-θuɾ-'viə","Ciencia",1),
("Odarz(ëj)","o-'daɾ-z(əʒ)","Feo (adjetivo)",1),
("Odarzu","o-'daɾ-zu","Fealdad",1),
("Ofüye","o-'fɯ-je","Aire",1),
("Ohichia","o-'xi-t͡ʃia","Adulto",1),
("Oihäb","oi-'xæb","Noche",1),
("Oizunü","oi-'zu-nɯ","Mal / maldad",1),
("Ojëga","o-'ʒə-ga","Desde (preposición)",1),
("Okamm(ëj)","o-'kam-m(əʒ)","Corrupto (política)  (adjetivo)",1),
("Okammüv","o-'kam-mɯv","Corrupción (política)",1),
("Okrëya","o-'kɾə-ja","Basura",1),
("Olyuna","o-'lju-na","Forma (morfológica)",1),
("Onilë","'o-ni-lə","Ahora (adverbio)",1),
("Opyëv(ëj)","o-'pjə-v(əʒ)","Inmenso (adjetivo)",1),
("Opyëvröc","o-'pjə-vɾʌθ","Inmensidad",1),
("Orcheb","oɾ-'t͡ʃeb","Sombra / Oscuridad",1),
("Ossira","os-'si-ɾa","Alumno / estudiante",1),
("Ovr(ëj)","o-'vɾ(əʒ)","Azul (adjetivo)",1),
("Ovrië","ʌ-'vɾi-ə","Azul",1),
("Oxen","o-'ʃen","Sur",1),
("Öyat(ëj)","ʌ-'ja-t(əʒ)","Violeta (adjetivo)",1),
("Öyatu","'ʌ-ja-tu","Violeta",1),
("Oyerx","o-'jeɾʃ","Cómo (adverbio)",1),
("Ozillë","'o-zil-lə","Abajo (adverbio)",1),
("Pabxua","pab-'ʃu-a","Derrota",1),
("Pahäj","pa-'xæʒ","Minuto",1),
("Paluëj","pa-'luəʒ","Sexo",1),
("Pärinë","pæ-'ɾi-nə","Calle",1),
("Pätsij","'pæ-t͡ʃiʒ","Aprender  (verbo)",1),
("Pavädir","pa-'væ-diɾ","Perder",1),
("Pedjev","ped-'ʒev","Nombre",1),
("Pëgic(ëj)","'pə-gi-θ(əʒ)","Celeste (adjetivo)",1),
("Pëgica","'pə-gi-θa","Celeste",1),
("Pirts(ëj)","piɾ-'t͡s(əʒ)","Dotado (adjetivo)",1),
("Pirtsan","piɾ-'t͡san","Dotar (verbo)",1),
("Pitëvaj","'pi-tə-vaʒ","Número",1),
("Plavät","pla-'væt","Brazo",1),
("Plivmut","'pliv-mut","Ser capaz (verbo)",1),
("Pofebrë","po-'fe-bɾə","Color",1),
("Prakots","pɾa-'kot͡s","Dibujo",1),
("Prakotsën","pɾa-'ko-t͡sən","Dibujar (verbo)",1),
("Prätzib","'pɾæt-zib","Aprobar (verbo)",1),
("Prëlis(ëj)","'pɾə-li-s(əʒ)","Alegre (adjetivo)",1),
("Prëlise","'pɾə-li-se","Alegría",1),
("Prëliztan","pɾə-'liz-tan","Alegrar (verbo)",1),
("Pronna","'pɾon-na","Ya (adverbio)",1),
("Pülla","'pɯl-la","Luna",1),
("Pülz","pɯlz","Dar (verbo)",1),
("Pürxutan","'pɯɾ-ʃu-tan","Tentar (verbo)",1),
("Puttüd","'put-tɯd","Pecho",1),
("Püzdya","'pɯz-dja","Edad",1),
("Räbägum","'ɾæ-bæ-gum","Tío/tía materno/a",1),
("Räginëv","'ɾæ-gi-nəv","Sobrino/  sobrina",1),
("Räizach","'ɾæi-zat͡ʃ","Caer (verbo)",1),
("Räjigum","'ɾæ-ʒi-gum","Tío/tía paterno/a",1),
("Räjir(ëj)","ɾæ-'ʒi-ɾ(əʒ)","Aterrorizado (adjetivo)",1),
("Räjiro","ɾæ-'ʒi-ɾo","Terror",1),
("Räjirokru","ɾæ-ʒi-'ɾo-kɾu","Aterrorizar (verbo)",1),
("Räkinnë","ɾæ-'kin-nə","Niña",1),
("Rallet","ɾal-'let","Gustar (verbo)",1),
("Ralvihü","'ɾal-vi-xɯ","Cuello",1),
("Rancudë","ɾan-'θu-də","Voluntad",1),
("Rävdam","'ɾæv-dam","Hermano/  hermana",1),
("Relirëb","ɾe-'li-ɾəb","Puntuar (verbo)",1),
("Rëuvux","ɾə-u-'vuʃ","Contar (números) (verbo)",1),
("Rikdem","'ɾik-dem","Meditar (verbo)",1),
("Rimiat","ɾi-'miat","Nada (adverbio)",1),
("Ritlëk","ɾi-'tlək","Pagar (verbo)",1),
("Rixhel","'ɾiʃ-xel","Hacer (verbo)",1),
("Röch(ëj)","ɾʌ-'t͡ʃ(əʒ)","Negro (adjetivo)",1),
("Röcheh","ɾʌ-'t͡ʃex","Negro",1),
("Rossir","'ɾos-siɾ","Estudiar (verbo)",1),
("Ruhöjë","ɾu-'xʌ-ʒə","Hogar",1),
("Rulnüd","'ɾul-nɯd","Vender (verbo)",1),
("Säcüt","'sæ-θɯt","Mi/mío (pronombre)",1),
("Sahöcyu","sa-'xʌ-θju","Escritura",1),
("Sahön","'sa-xʌn","Escribir (verbo)",1),
("Sahön(ëj)","sa-'xʌ-n(əʒ)","Escrito (adjetivo)",1),
("Sahötsë","sa-'xʌ-t͡sə","Escrito / texto",1),
("Säinz","sæinz","Poner / colocar (verbo)",1),
("Sät","sæt","Yo (pronombre)",1),
("Sätsud","'sæ-t͡sud","Libertad",1),
("Sätsud(ëj)","sæ-'t͡su-  d(əʒ)","Libre (adjetivo)",1),
("Savlar","'sa-vlaɾ","Nariz",1),
("Sazit","sa-'zit","Piedra",1),
("Sazüx","sa-'zɯʃ","Ropa",1),
("Sënna","'sən-na","Sueño",1),
("Sënnoh","sən-'nox","Soñar (verbo)",1),
("Sigorië","si-go-riə","Trueno",1),
("Sijka","'siʒ-ka","Junto a (preposición)",1),
("Sijört","si-'ʒʌɾt","Susto",1),
("Sikinnë","si-'kin-nə","Niño",1),
("Silün","si-'lɯn","Agua",1),
("Sirnon","'siɾ-non","Casi (adverbio)",1),
("Somech","so-'met͡ʃ","Furia  / ira",1),
("Somech(ëj)","so-'met͡ʃ(əʒ)","Furioso / enfurecido  (adjetivo)",1),
("Somechfas","so-'met͡ʃ-fas","Enfurecer (verbo)",1),
("Sotsüd","so-'t͡sɯd","Saltar (verbo)",1),
("Srirëh","'sɾi-ɾəx","Controlar (verbo)",1),
("Srirëun","'sɾi-ɾəun","Control",1),
("Süjält","sɯ-'ʒælt","Signo / símbolo",1),
("Täche","'tæ-t͡ʃe","Cabeza",1),
("Taijë","'tai-ʒə","Adiós",1),
("Täkrüh","tæ-'kɾɯx","Deporte",1),
("Tavoik","ta-'voik","Deprisa (adverbio)",1),
("Tavoik(ëj)","ta-'voi-k(əʒ)","Rápido / veloz (adjetivo)",1),
("Tavoiküa","ta-voi-'kɯ-a","Rapidez",1),
("Tëxküz","təʃ-'kɯz","Navegar (verbo)",1),
("Tëxküzat","təʃ-'kɯ-zat","Navegante",1),
("Tiröt","'ti-ɾʌt","Señor / señora",1),
("Tizacel","ti-'za-θel","Lastimar / herir (verbo)",1),
("Tlets(ëj)","'tle-t͡s(əʒ)","Naranja (adjetivo)",1),
("Tletsiën","'tle-t͡siən","Naranja",1),
("Tömnul","tʌm-'nul","Letra",1),
("Tömzuit","tʌm-'zuit","Alfabeto",1),
("Trädiv","tɾæ-'div","Poder (verbo)",1),
("Trill(ëj)","tɾil-'l(əʒ)","Amarillo (adjetivo)",1),
("Trillyö","'tɾil-ljʌ","Amarillo",1),
("Trivjë","'tɾiv-ʒə","Mañana (momento del día)",1),
("Trügëj","'tɾɯ-gəʒ","Padres/  madres",1),
("Trumnë","'tɾum-nə","Planeta",1),
("Tsarij","t͡sa-'ɾiʒ","Saber (verbo)",1),
("Tsimmër","'t͡sim-məɾ","Sangre",1),
("Tsürëc","'t͡sɯ-ɾəθ","Nacer (verbo)",1),
("Tuhjim","'tux-ʒim","Construir (verbo)",1),
("Türat","tɯ-'ɾat","Abrir (verbo)",1),
("Tuzäre","tu-'zæ-ɾe","Alrededor (adverbio)",1),
("Täche","'tæ-t͡ʃe","Cabeza",1),
("Ubatiz","u-ba-'tiz","Pierna",1),
("Ucemër","u-'θe-məɾ","Demasiado (adverbio)",1),
("Ucöfich","u-'θʌ-fit͡ʃ","Cobre",1),
("Udrän","u-'dɾæn","Después / luego (adverbio)",1),
("Ugrea","u-'gɾe-a","Corazón",1),
("Üjami","ɯ-'ʒa-mi","Tarde (adverbio)",1),
("Ujönnë","u-'ʒʌn-nə","Niños / niñas",1),
("Ukämi(ëj)","u-'kæ-mi(əʒ)","Dorado (adjetivo)",1),
("Ukämiol","u-'kæ-miol","Dorado",1),
("Ukän","u-'kæn","Oro",1),
("Ükardih","'ɯ-kaɾ-dix","Reino (Estado monárquico)",1),
("Ükart","'ɯ-kaɾt","Rey",1),
("Ukimë","u-'ki-mə","Arriba (adverbio)",1),
("Ulirach","u-'li-ɾat͡ʃ","Siguiente / posterior",1),
("Ünn(ëj)","'ɯn-n(əʒ)","Pequeño / chico (adjetivo)",1),
("Ürokye","ɯ-'ɾo-kje","Otro (pronombre)",1),
("Ussirë","us-'si-ɾə","Galaxia",1),
("Utivcha","u-'tiv-t͡ʃa","Igual (adverbio)",1),
("Uvira","u-'vi-ɾa","Hasta (preposición)",1),
("Üvitëcu","ɯ-'vi-tə-θu","Versículo",1),
("Uvöira","u-'vʌi-ɾa","Adentro (adjetivo)",1),
("Uyäbil","u-'jæ-bil","Espalda",1),
("Uyertü","u-'jeɾ-tɯ","Vocal",1),
("Uziova","u-'zio-va","Este",1),
("Valpë","'val-pə","Lugar",1),
("Väptad(ëj)","væp-ta-'d(əʒ)","Primero (adjetivo)",1),
("Vareiëch","va-'ɾei-ət͡ʃ","Logia",1),
("Vëktal","'vək-tal","Fuerza (física)",1),
("Versëh","'veɾ-səx","Perdonar (verbo)",1),
("Versuë","'ver-suə","Perdón",1),
("Vëxektlem","'və-ʃek-tlem","Fuerza Cósmica",1),
("Vëz","vəz","Sí  (adverbio)",1),
("Vezkinëj","'vez-ki-nəʒ","Hijos/hijas",1),
("Vihkire","vix-'ki-ɾe","Oración / frase",1),
("Visgër","'vis-gəɾ","Cocinar (verbo)",1),
("Vissran","'vis-sɾan","Cocina",1),
("Vlantë","'vlan-tə","Enseguida (adverbio)",1),
("Vocij","vo-'θiʒ","Mal (adverbio)",1),
("Vocij(ëj)","vo-'θi-ʒ(əʒ)","Malo (adjetivo)",1),
("Vör","vʌɾ","Y (conjunción)",1),
("Vörche","'vʌɾ-t͡ʃe","Hacia (preposición)",1),
("Vörkal","vʌɾ-'kal","Buscar (verbo)",1),
("Vötsüa","vʌ-'t͡sɯ-a","Razón (capacidad)",1),
("Vrichmöl","'vɾit͡ʃ-mʌl","Estado / país (política)",1),
("Vubrëg","vu-'bɾəg","Llegar (verbo)",1),
("Vüryat","vɯ-'ɾjiat","Ayer",1),
("Vyëz(ëj)","'vjə-z(əʒ)","Alienígena /  extraterrestre (adjetivo)",1),
("Vyëzi","'vjə-zi","Persona alienígena /  persona extraterrestre",1),
("Xäcil","'ʃæ-θil","Beber  (verbo)",1),
("Xahurd","ʃa-'xuɾd","Tierra (territorio)",1),
("Xasticut","ʃas-'ti-θut","Órbita",1),
("Xatsia","'ʃa-t͡sia","Eso / ese (pronombre)",1),
("Xatspë","'ʃat͡s-pə","Ahí (adverbio)",1),
("Xavrëts","ʃa-'vɾət͡s","Tocar (verbo)",1),
("Xazüt","ʃa-'zɯt","Bebida",1),
("Xëkits","ʃə-'kit͡s","Percibir (verbo)",1),
("Xëkitsö","'ʃə-ki-t͡sʌ","Percepción",1),
("Xelem","ʃe-'lem","Cosmos / universo",1),
("Xelie","'ʃe-lie","Esto / este (pronombre)",1),
("Xelpë","'ʃel-pə","Aquí (adverbio)",1),
("Xënnäl","ʃən-'næl","Encontrar (verbo)",1),
("Ximüligu","ʃi-mɯ-'li-gu","Lindura",1),
("Ximür(ëj)","'ʃi-mɯ-ɾ(əʒ)","Lindo (adjetivo)",1),
("Xirsöd","'ʃiɾ-sʌd","Hijo",1),
("Xirvezi","ʃiɾ-'ve-zi","Nieto",1),
("Xörlëm","'ʃʌɾ-ləm","Matar (verbo)",1),
("Xrällats","'ʃɾæl-lat͡s","Entregar (verbo)",1),
("Xuarich","ʃua-'ɾit͡ʃ","Nadie (pronombre)",1),
("Xübrëh","ʃɯ-'bɾəx","Existir (verbo)",1),
("Xübricea","ʃɯ-bɾi-'θe-a","Existencia",1),
("Xujikariannë","ʃu-ʒi-ka-'ɾian-nə","Constitución",1),
("Xusena","ʃu-'se-na","Mientras (adverbio)",1),
("Yächëirt","jæ-'t͡ʃə-iɾt","Registro (del habla)",1),
("Yadila","'ja-di-la","Madera",1),
("Yäjiba","jæ-'ʒi-ba","Adelante (adverbio)",1),
("Yaliözah","ja-'liʌ-zax","Materia",1),
("Yallenkrë","jal-'len-kɾə","Imperio",1),
("Yaxa","'ja-ʃa","Árbol",1),
("Yëbdëiv","jəb-'dəiv","Período / intervalo",1),
("Yëcla","'jə-θla","Cielo",1),
("Yehyach","je-'xjat͡ʃ","Adjetivo",1),
("Yelifraya","je-li-'fɾa-ja","Población",1),
("Yemöa","je-'mʌ-a","Bebé",1),
("Yëren","'jə-ɾen","Siempre (adverbio)",1),
("Yëzil","jə-'zil","De nuevo / otra vez  (adverbio)",1),
("Yöbär","'jʌ-bæɾ","Segundo (tiempo)",1),
("Yobiër","jo-'biəɾ","Lejos (adverbio)",1),
("Yobiër(ëj)","jo-'biə-ɾ(əʒ)","Lejano (adjetivo)",1),
("Yöjuc","'jʌ-ʒuθ","Rosa",1),
("Yöjuc(ëj)","jʌ-'ʒu-θ(əʒ)","Rosado (adjetivo)",1),
("Yorun(ëj)","jo-'ɾu-n(əʒ)","Delicioso (adjetivo)",1),
("Yoruna","jo-'ɾu-na","Delicia",1),
("Yu","ju","De (preposición)",1),
("Yukrätda","ju-'kɾæt-da","Imagen",1),
("Yunteö","jun-te-ʌ","Cabello",1),
("Yüpat","jɯ-'pat","Bastante (adverbio)",1),
("Zäldorë","zæl-'do-rə","Sociedad",1),
("Zannenföt","'zan-nen-fʌt","Iglesia",1),
("Zäta","'zæ-ta","Nosotros (pronombre)",1),
("Zätcü","'zæt-θɯ","Nuestro (pronombre)",1),
("Zei","zei","Expresión de sorpresa  (interjección)",1),
("Zëjau","zə-'ʒa-u","Amor",1),
("Zëjav","zə-'ʒav","Amar (verbo)",1),
("Zertëm","'zeɾ-təm","Iluminar (verbo)",1),
("Zertië","'zeɾ-tiə","Luz",1),
("Zied","zied","Bajar (verbo)",1),
("Ziesurt","'zie-surt","Verbo",1),
("Zimianël","zi-'mia-nəl","República",1),
("Zissal","zis-'sal","Entrar (verbo)",1),
("Zojoa","zo-'ʒo-a","Aquello / aquel (cercano)  (pronombre)",1),
("Zojpë","'zoʒ-pə","Allí (cernano) (adverbio)",1),
("Zokküjig","zok-'kɯ-ʒig","Generación",1),
("Zöyac","'zʌ-jaθ","Mejor (adverbio)",1),
("Zucikäm","zu-θi-'kæm","Alma (concepto biofísico)",1),
("Zucpë","'zuθ-pə","Allí (lejano) (adverbio)",1),
("Zucua","zu-'θu-a","Aquello /aquel (lejano)  (pronombre)",1),
("Züdurhe","zɯ-'duɾ-xe","Verduras / vegetales",1),
("Züfäbin","zɯ-'fæ-bin","Sentimientos",1),
("Züfäp","zɯ-'fæp","Sentir (verbo)",1),
("Zuhjës","'zux-ʒəs","Sentar (verbo)",1),
("Zut","zut","En (preposición)",1);